### ISSUE TITLE
how to edit the default title ?

### ISSUE THREAD

**Issue by mnyon** [frostime/sy-theme-trends#1]
Great work! and how to edit the title content ? ( Trends in Siyuan Notes

**Comment by frostime** [comment]
Hi! The banner upon the document's title is actually a pseudo-element attached to `.protyle-title` (i.e. the document's title class).

You can see the css code in https://github.com/frostime/sy-theme-trends/blob/main/style/title.css

The content of `Trends in SiYuan` is a background image in svg format, in `src/trends.svg`. This svg file is exported from a drawio file in `src/trends.drawio`.

**Comment by frostime** [comment]
If there is no more question, I'll close this now. You can still ask in this thread. 😊

**Comment by mnyon** [comment]
🎉Really thanks for the help ! Great theme,It makes me feels like academic writing, Hope keeping develop this theme! Thanks again.
